In [19]:
import numpy as np
import pandas as pd
from PIL import Image
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter
from wordcloud import WordCloud
from konlpy.tag import Okt
from collections import defaultdict

In [27]:
df = pd.read_excel('data/IPC전체.xlsx')
df.head()

,↑,코드,한글,노트,경고,정의,개인 메모,CPC 매핑,기타
0,NaN,A,생활필수품,False,False,False,NaN,NaN,NaN
1,NaN,A01*,농업,False,False,False,NaN,NaN,NaN
2,NaN,A01,농업; 임업; 축산; 수렵; 포획; 어업,False,False,False,NaN,NaN,NaN
3,NaN,A01B,"농업 또는 임업에 있어서의 토작업; 농기구 또는 기구의 부품, 세부 또는 부속구 일...",False,False,False,NaN,NaN,NaN
4,NaN,A01C,"식부; 파종; 시비(농기계 또는 도구의 부품, 세부 사항 또는 부속품, 일반적으로 ...",False,False,False,NaN,NaN,NaN

In [28]:
df = df[['코드', '한글']]

In [29]:
df.head()

     코드                                                 한글
0     A                                              생활필수품
1  A01*                                                 농업
2   A01                             농업; 임업; 축산; 수렵; 포획; 어업
3  A01B  농업 또는 임업에 있어서의 토작업; 농기구 또는 기구의 부품, 세부 또는 부속구 일...
4  A01C  식부; 파종; 시비(농기계 또는 도구의 부품, 세부 사항 또는 부속품, 일반적으로 ...

In [30]:
df['IPC'] = df['코드']
df['설명'] = df['한글']
df = df.drop('한글', axis=1)
df = df.drop('코드', axis=1)
df.head()

    IPC                                                 설명
0     A                                              생활필수품
1  A01*                                                 농업
2   A01                             농업; 임업; 축산; 수렵; 포획; 어업
3  A01B  농업 또는 임업에 있어서의 토작업; 농기구 또는 기구의 부품, 세부 또는 부속구 일...
4  A01C  식부; 파종; 시비(농기계 또는 도구의 부품, 세부 사항 또는 부속품, 일반적으로 ...

In [31]:
df['설명'] = df['설명'].apply(lambda x: x[:50] if len(x) >= 50 else x)

In [32]:
df.to_excel('data/IPC코드설명표.xlsx', index=True)